export type MarketType = {
  callbackAddr: string;
  capacity: string;
  capacityInQuote: boolean;
  conclusion: number;
  createdAt: string;
  id: string;
  isLive: boolean;
  marketType: string;
  maxPayout: string;
  owner: string;
  payoutToken: string;
  price: string;
  quoteToken: string;
  scale: string;
  start: number;
  updatedAt: string;
  vesting: number;
  vestingType: string;
  bondMarketPrice: number;
  discount: number;
  __v: number;
  sold: string;
  askingPrice: number;
  actualMarketPrice: number;
};
